#%RAML 1.0
title: USERS-EXP-API
version: 1.0.0
description: Referred from Reqres API

/users:
  get:
  post:
  /{id}:
    get:
    patch:
    put:
    delete:
      
/resource:
  get:
  /{id}:
    get:
    patch:
    put:
    delete:

/login:
  post:

/logout:
  post:   